name: ENA S4 capture
on:
  schedule:
    - cron: "0 21 * * *"   # UTC 21:00 = 北京时间 05:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npx playwright install --with-deps chromium
      - run: npm run fetch
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
