name: ENA S4 capture

on:
  # 每天 UTC 21:00 运行（= 北京时间 05:00）
  schedule:
    - cron: "0 21 * * *"
  # 手动触发按钮（Actions 页面里的 “Run workflow”）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Proxy sanity check (temporary)
        run: |
          echo "Proxy check..."
          # 遮挡一下日志里的密码
          echo "${PROXY_SERVER}" | sed -E 's#(://[^:/]+:)[^@]+@#\1****@#'
          # 如果你采用分开填用户名/密码，这里会用 -U 传；如果你把账号密码写在 PROXY_SERVER 里也OK
          curl -sS -m 15 -x "${PROXY_SERVER}" ${PROXY_USERNAME:+-U "${PROXY_USERNAME}:${PROXY_PASSWORD}"} https://ifconfig.me
          echo
          curl -sS -m 20 -I -x "${PROXY_SERVER}" ${PROXY_USERNAME:+-U "${PROXY_USERNAME}:${PROXY_PASSWORD}"} https://app.ethena.fi/overview || true
        env:
          PROXY_SERVER:   ${{ secrets.PROXY_SERVER }}
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Fetch ENA S4 and push to Google Sheet
        run: npm run fetch
        env:
          # 必填：GAS 的 Web App URL（在 Apps Script 部署得到）
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}

          # 代理（“二选一”用法）：
          # 方式 A：分开填这三项（PROXY_SERVER 必填；后两项若没账号密码可留空）
          PROXY_SERVER:   ${{ secrets.PROXY_SERVER }}
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

          # 方式 B：如果你把账号密码直接写在 URL 里（例如 http://user:pass@host:port），
          # 只需要在 Secrets 里建 PROXY_SERVER 一项即可，USERNAME/PASSWORD 可不建或留空。
